# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
---
version: 2
project_name: cruise

before:
  hooks:
    - go mod tidy

builds:
  - binary: cruise
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

nfpms:
  - package_name: cruise
    homepage: https://cruise-org.github.io
    maintainer: NucleoFusion <lakshit.singh.mail@gmail.com>
    description: |-
      Cruise is a powerful, intuitive, and fully-featured container management TUI (Terminal
      User Interface)
    license: Apache-2.0
    formats:
      - rpm
      - deb

homebrew_casks:
  - name: cruise
    url:
      template: "https://github.com/cruise-org/cruise/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      verified: "github.com/cruise-org/cruise"
    homepage: https://cruise-org.github.io
    description: |-
      Cruise is a powerful, intuitive, and fully-featured container management TUI (Terminal
      User Interface)
    skip_upload: false
    directory: Casks
    license: Apache-2.0
    repository:
      owner: cruise-org
      name: homebrew-tap
      branch: main

aurs:
  - name: cruise-bin
    homepage: https://cruise-org.github.io
    maintainers:
      - "NucleoFusion <lakshit.singh.mail@gmail.com>"
    description: |-
      Cruise is a powerful, intuitive, and fully-featured container management TUI (Terminal
      User Interface)
    license: "Apache-2.0"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/cruise-bin.git"
    optdepends:
      - trivy
      - grype
    package: |-
      install -Dm755 "./cruise" "${pkgdir}/usr/bin/cruise"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/cruise/LICENSE"

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
